# Generated by Django 4.0.5 on 2022-07-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=200)),
                ('shorten', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(verbose_name='created at')),
            ],
        ),
    ]
