# Generated by Django 4.0.5 on 2022-07-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
